-- Tạo bảng lưu trữ sơ đồ sân khấu dạng JSON
CREATE TABLE EVENT_SEAT_MAPS (
    EVENT_ID NUMBER PRIMARY KEY,
    MAP_DATA CLOB CHECK (MAP_DATA IS JSON), -- Oracle 12c+ support JSON constraint check
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_MAP_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(ID) ON DELETE CASCADE
);
