-- Migration V7: Create REVIEWS table
CREATE TABLE REVIEWS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID INT NOT NULL,
    EVENT_ID INT NOT NULL,
    RATING INT CHECK (RATING >= 1 AND RATING <= 5),
    COMMENT_TEXT CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_REVIEW_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_REVIEW_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(ID)
);
